deprecated_final/flask_app/pokemon/routes.py
from flask import Blueprint, render_template, url_for, redirect, request, flash
from flask_login import current_user

from .. import poke_client
from ..forms import PokemonReviewForm, SearchForm, AddPokemonForm, RemovePokemonForm
from ..models import User, Review, TeamMember
from ..utils import current_time

pokemon = Blueprint('pokemon', __name__)

@pokemon.route('/', methods=['GET', 'POST'])
def index():
    form = SearchForm()

    if form.validate_on_submit():
        return redirect(url_for("pokemon.pokemon_detail", pokemon=form.search_query.data))

    return render_template("index.html", form=form)


@pokemon.route("/search-results/<query>", methods=["GET"])
def query_results(query):
    try:
        results = poke_client.get_pokemon_info(query)
    except ValueError as e:
        flash(str(e))
        return redirect(url_for("pokemon.index"))

    return render_template("pokemon_detail.html", results=results)


@pokemon.route("/pokemon/<pokemon>", methods=["GET", "POST"])
def pokemon_detail(pokemon):
    try:
        result = poke_client.get_pokemon_info(pokemon)
    except ValueError as e:
        flash(str(e))
        return redirect(url_for("users.login"))

    addForm = AddPokemonForm()
    if addForm.validate_on_submit() and current_user.is_authenticated:
        team = TeamMember(
            trainer = current_user,
            pokemon = addForm.pokemon.data,
        )
        team.save()

        return redirect(url_for("users.team", username=current_user.username))

    form = PokemonReviewForm()
    if form.validate_on_submit() and current_user.is_authenticated:
        if len(form.text.data) >= 5:
            review = Review(
                Trainer=current_user._get_current_object(),
                content=form.text.data,
                date=current_time(),
                pokemon=pokemon,
            )
            review.save()
            return redirect(request.path)

    reviews = Review.objects(pokemon=pokemon)
    return render_template(
        "pokemon_detail.html", pokemon=result, reviews=reviews, addForm = addForm, form=form)

@pokemon.route("/user/<username>")
def user_detail(username):
    user = User.objects(username=username).first()
    reviews = Review.objects(Trainer=user)

    team = user.team

    return render_template("user_detail.html", username=username, reviews=reviews, team=team)

deprecated_final/flask_app/users/routes.py
from flask import Blueprint, redirect, url_for, render_template, flash, request
from flask_login import current_user, login_required, login_user, logout_user
from flask_mongoengine import MongoEngine

from .. import bcrypt
from ..email import send_email
from ..token import generate_confirmation_token, confirm_token
from ..forms import RegistrationForm, LoginForm, UpdateUsernameForm, UpdateProfilePicForm, ValidationError, AddPokemonForm
from ..models import User, TeamMember

import io
import base64

users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("pokemon.index"))

    form = RegistrationForm()
    if form.validate_on_submit():
        hashed = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        user = User(username=form.username.data, email=form.email.data, password=hashed)
        user.save()
        
        # send conformation email
        msg = "Congratuations on becoming a new trainer! If you did not sign up for this, we do not care. Good luck getting unsubscribed. Please contact 210-426-6079."
        if not current_user is not None:
        # mail.send(msg)
            token = generate_confirmation_token(user.email)
            confirm_url = url_for("users.confirm_email", token=token, _external=True)
            confirm_template = render_template("confirm.html", confirm_url=confirm_url)
            send_email(user.email, msg, confirm_template)

        return redirect(url_for("users.login"))

    return render_template("register.html", title="Register", form=form)

@users.route("/confirm/<token>")
@login_required
def confirm_email(token):
    try:
        email = confirm_token(token)
        user = User.objects(email=email).first()
        if user.confirmed is False:
            current_user.modify(confirmed=True)
            current_user.save()
    except:
        flash("This confirmation link is invalid.")
    return redirect(url_for('users.account'))
    # return render_template("account.html")

@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("pokemon.index"))

    form = LoginForm()
    try:
        if form.validate_on_submit():
            user = User.objects(username=form.username.data).first()

            if user is not None and bcrypt.check_password_hash(
                user.password, form.password.data
            ):
                login_user(user)
                return redirect(url_for("users.account"))
            else:
                flash("Login failed. Check your username and/or password")
                return redirect(url_for("users.login"))
    except (ValidationError, ValueError) as e:
        return redirect(url_for('login'), error=str(e))

    return render_template("login.html", title="Login", form=form)


def get_b64_img(username):
    user = User.objects(username=username).first()
    bytes_im = io.BytesIO(user.pfp.read())
    image = base64.b64encode(bytes_im.getvalue()).decode()
    return image

@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    update_user_form = UpdateUsernameForm()
    pfp_update_form = UpdateProfilePicForm() 

    try: 
        if update_user_form.validate_on_submit(): #I believe it will already validate username doesn't exist
            current_user.modify(username=update_user_form.username.data)
            current_user.save()
            return redirect(request.path)
        
        if pfp_update_form.validate_on_submit():
            img = pfp_update_form.pfp.data
            content_type = 'images/jpg'

            if current_user.pfp.get() is None:
                current_user.pfp.put(img.stream, content_type=content_type)
            else:
                current_user.pfp.replace(img.stream, content_type=content_type)
            current_user.save()

            return redirect(url_for('users.account'))
    except (ValidationError, ValueError) as e:
        return redirect(url_for('login'), error=str(e))

    image = get_b64_img(current_user.username)

    return render_template(
        "account.html",
        title="Account",
        username_form=update_user_form,
        pfp_update_form=pfp_update_form, 
        image=image
    )

@users.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for("pokemon.index"))

@users.route("/user/<username>")
def user_detail(username):
    user = User.objects(username=username).first()
    team = user.team

    return render_template("user_detail.html", username=username, team=team, image=get_b64_img(username))

@users.route('/<username>/team', methods=['GET', 'POST'])
def team(username):
    form = AddPokemonForm()

    if form.validate_on_submit():
        team = TeamMember(
            trainer = current_user,
            pokemon = form.pokemon.data,
        )
        team.save()
        #current_user.modify(username=update_user_form.username.data)
        #    current_user.save()
        return redirect(request.path)

    members = TeamMember.objects(trainer=current_user)

    return render_template("team_detail.html", trainer=username, form=form, team=members)

@users.route('/about')
def about():
    return render_template("about.html")

deprecated_final/flask_app/templates/about.html
{% extends "header.html" %}
{% block content %}

<div class="col">
    <h2> Welcome to Lily Mueller and Eric Fields' CMSC388J Final Project</h2>
    <body> This project allows people to create an account on which they can 
            search for pokemon and add them to their team. They can also comment
            on individual pokemon and see other people's comments on the pokemon.
            They can view many different aspects about a pokemon before adding to 
            their team to get a good idea of what they would be getting from 
            that pokemon. 

            <a href="{{ url_for('users.login') }}">
                <h4>Click here to login</h4>
            </a>
    </body>
</div>

{% endblock %}

deprecated_final/flask_app/templates/account.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        {# Profile picture #}
        <img class="pfp" src="data:image/png;base64,{{image}}" alt="image">
    </div>
</div>
<div class="row">
    <div class="col">
        <h1>Hi, {{ current_user.username }}! Ready to train?</h1>
    </div>
</div>
<div class="row">
    <div class="col">
        <form action="" method="post">
            {{ username_form.csrf_token }}
            <div class="form-group">
                {{ username_form.username.label(class="form-control-label") }}
                {{ username_form.username(class="form-control form-control-lg") }}

                {% if username_form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in username_form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ username_form.submit }}
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col">
        
        {# Profile Picture Update Form #}
        <form method="POST" action="" enctype="multipart/form-data">
        {{ pfp_update_form.csrf_token }}
        <div class="form-group">
            {{ pfp_update_form.pfp.label }}
            {{ pfp_update_form.pfp(class="form-control") }}
    
            {% if pfp_update_form.errors %}
            <div class="alert alert-warning" role="alert">
            {% for error in pfp_update_form.errors %}
            <span>{{ error }}</span>
            {% endfor %}
            </div>
            {% endif %}
    
        </div>
        {{ pfp_update_form.submit() }}
        </form>
    </div>
</div>

<div class="row">
    <div class="col">
        {# Link to see all of the current user's reviews. #}
        <a href="{{ url_for('users.team', username=current_user.username) }}">
            <h4>Click here to meet your team!</h4>
        </a>
    </div>
</div>

{% endblock %}>

deprecated_final/flask_app/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
     <link rel="stylesheet" href="{{ url_for('static', filename='custom.css') }}">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Pokemon Team Builder</title>
    {% endif %}
</head>
<body>
    {% block header %}
    <h1>Overrideable Content</h1>
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

deprecated_final/flask_app/templates/confirm.html
<p>You're so close to being a trainer! Just click on this link to confirm! </p>
<p><a href="{{ confirm_url }}">{{ confirm_url }}</a></p>

deprecated_final/flask_app/templates/header.html
{% extends "base.html" %}
{% block header %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{{ url_for('pokemon.index') }}">Pokemon Team Builder</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
            {% if current_user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.account') }}">
                    Account
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.logout') }}">
                    Logout
                </a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.login') }}">
                    Login
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.register') }}">
                    Register
                </a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>


<div class="container">
    {% block content %}{% endblock %}
</div>
{% endblock %}

deprecated_final/flask_app/templates/index.html
{% extends "header.html" %}
{% block content %}

<div class="row">
    <div class="col">
        <form action="/" class="form-inline my-2 my-lg-0" method="POST">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-info">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

            <div class="col">
                <h2> Please use the search bar to search for pokemon by name! Then you can review them </h2>

                <a href="{{ url_for('users.about') }}">
                    <h4>Click here to see the about page!</h4>
                </a>
            </div>

            {{ form.csrf_token }}
            {{ form.search_query(class="form-control", placeholder="Search") }}

            {% if form.search_query.errors %}
            <div class="alert alert-warning" role="alert">
                {% for error in form.search_query.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}

            {{ form.submit(class="btn btn-outline-success") }}
        </form>
    </div>
</div>
{% endblock %}

deprecated_final/flask_app/templates/login.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <h2>Log In</h2>
    </div>
</div>
<div class="row">
    <div class="col">
        <b> Are you still not a Trainer and want to be? </b> Then <a href="{{ url_for('users.register') }}"> become one here!</a>
    </div>
</div>
<div class="row">
    <div class="col">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-info">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        <form action="" method="post">
            {{ form.csrf_token }}
            <div class="form-group">
                {{ form.username.label(class="form-control-label green-text") }}
                {{ form.username(class="form-control form-control-md") }}

                {% if form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {{ form.password(class="form-control form-control-lg") }}

                {% if form.password.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.submit(class="form-control form-control-lg") }}
            </div>
        </form>
    </div>
</div>
{% endblock %}

deprecated_final/flask_app/templates/pokemon_detail.html
{% extends "header.html" %}
{% block content %}

{% if error_msg %}
<b>{{ error_msg }}</b>
{% endif %}

{% if pokemon %}

{# Display card for the movie details #}
<div class="row">
  <div class="col">
    <div class="card text-center">
      <div class="card-header">
        {{ pokemon['name'] }}
      </div>
      <div class="card-body">
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><b>Height:</b> {{ pokemon['height'] }}</li>
          <li class="list-group-item"><b>Weight:</b> {{ pokemon['weight'] }}</li>
          <li class="list-group-item"><b>Base Experience:</b> {{ pokemon['base_exp'] }}</li>
          <li class="list-group-item"><b>Moves:</b> {% for m in pokemon['moves'] %}
              <li><b>{{ m }}</b></li>
            {% endfor %}</li>
        </ul>
      </div>
    </div>
  </div>
</div>

{# Reviews #}
<div class="row">
  <div class="col-md-12">
    <h1> Reviews <small class="float-right">{{ reviews|length }} reviews</small></h1>
    <ul class="media-list">
      {% for review in reviews %}
      <li class="media review-item">
        <div class="media-body">
          <span class="float-right">
            <small>{{ review.date }}</small>
          </span>
          <a href="{{ url_for('pokemon.user_detail', username=review.Trainer.username) }}">
            <strong>@{{ review.Trainer.username }}'s review of {{ review.pokemon }}</strong>
          </a>
          <p>
            {{ review.content }}
          </p>
        </div>
      </li>
      {% endfor %}
    </ul>
  </div>
</div>

{% if current_user.is_authenticated %}

{# Movie review submission form #}
<div class="row">
  <div class="col">
    <form method="POST" action="">
      {{ form.csrf_token }}
      <div class="form-group">
        {{ form.text.label }}
        {{ form.text(class="form-control") }}

        {% if form.text.errors %}
        <div class="alert alert-warning" role="alert">
          {% for error in form.text.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% endif %}

      </div>
      {{ form.submit() }}
    </form>
  </div>
</div>
{% endif %}
{% endif %}
{% endblock content %}

deprecated_final/flask_app/templates/query.html
{% extends "header.html" %}
{% block content %}

<div class="container-fluid">
    {% for result in results %}
    <div class="media">
        <img src="{{ pokemon.image_url }}" 
        class="mr-3 movie" alt="missing">
        <div class="media-body">
        <h5 class="mt-0"><a href="{{ url_for('pokemon.pokemon_detail', pokemon=result) }}">{{ result }}</a> </h5>
        </div>
    </div>
    {% endfor %}
</div>


{% if error_msg %}
    <p>{{ error_msg }}</p>
{% endif %}

{% endblock %}

deprecated_final/flask_app/templates/register.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <h2>Register to become a Trainer! </h2>
    </div>
</div>
<div class="row">
    <div class="col">
        If you already a trainer, then just <a href="{{ url_for('users.login') }}">Log in to assemble your team!</a>
    </div>
</div>
<!-- Registration Form: -->
<div class="row">
    <div class="col">
        <form action="" method="post">
            {{ form.csrf_token }}
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}
                {{ form.username(class="form-control form-control-lg") }}
                {% if form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {{ form.email(class="form-control form-control-lg") }}
                {% if form.email.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {{ form.password(class="form-control form-control-lg") }}
                {% if form.password.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                {{ form.confirm_password(class="form-control form-control-lg") }}
                {% if form.confirm_password.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.confirm_password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.submit(class="form-control form-control-lg") }}
            </div>
        </form>
    </div>
</div>

{% endblock %}

deprecated_final/flask_app/templates/team_detail.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
            <h1> Your FABULOUS team! </h1>
            <ul class="media-list">
                {% for member in team %}
                <li class="media review-item">
                    <div class="media-body">
                        <span class="float-right">
                            {{ member.pokemon }}
                        </span>
                    </div>
                </li>
                {% endfor %}
            </ul>
    </div>
</div>

<div class="row">
    <div class="col">
        <h2> Add Pokemon: </h2>
        <form action="" method="post">
            {{ form.csrf_token }}
            <div class="form-group">
                {{ form.pokemon.label(class="form-control-label") }}
                {{ form.pokemon(class="form-control form-control-lg") }}
                {% if form.pokemon.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.pokemon.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
        </form>
    </div>
</div>

{% endblock %}

deprecated_final/flask_app/templates/user_detail.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <img class="propic" src="data:image/png;base64,{{image}}" alt="image">
    </div>
    <div class="col">
        <h2>{{ username }}'s Homepage</h2>
    </div>
</div>
<div class="row">
    <div class="col">
            <h1> Your FABULOUS team! </h1>
            <ul class="media-list">
                {% for pokemon in team %}
                <li class="media review-item">
                    <div class="media-body">
                        <span class="float-right">
                            <small>{{ pokemon['name'] }}</small>
                        </span>
                        <strong>For: <a href="{{ url_for('pokemon.pokemon_detail', pokemon=pokemon['name']) }}">
                            </a>
                        </strong>
                    </div>
                </li>
                {% endfor %}
            </ul>
    </div>
</div>
{% endblock %}